### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by leryan36** [jack-tobin/mvgarch#1]
Hello, thank for for sharing your work. It seems that at the end of your test.py, forecasted returns and forecasted covariances are set equal to the same variable.

# extract aggregated simple return and covariance forecasts
forecast_rets = dcc.fc_cov_agg_simp
forecast_covs = dcc.fc_cov_agg_simp

**Comment by jack-tobin** [comment]
Thanks for raising this! I've fixed the issue
